#define NUMBER_FACES 17
#define INVALID_FACE -1
#define AHEGAO 0
#define COLD 1
#define CONFUSED 2
#define DEAD 3
#define FROWN 4
#define GLAD 5
#define GRIN 6
#define HAPPY 7
#define HOT 8
#define OWO 9
#define POLITE 10
#define SHOCK 11
#define SKULL 12
#define SPEECHLESS 13
#define SURPRISED 14
#define UNSURE 15
#define UWU 16

const int8_t nextFaces[][3] = {
  {UNSURE, INVALID_FACE, INVALID_FACE}, //AHEGAO
  {AHEGAO, UNSURE, INVALID_FACE}, //COLD
  {OWO, SPEECHLESS, INVALID_FACE}, //CONFUSED
  {FROWN, SKULL, INVALID_FACE}, //DEAD
  {DEAD, SPEECHLESS, INVALID_FACE}, //FROWN
  {HAPPY, OWO, UWU}, //GLAD
  {HAPPY, POLITE, SPEECHLESS}, //GRIN
  {GLAD, GRIN, SURPRISED}, //HAPPY
  {SURPRISED, INVALID_FACE, INVALID_FACE}, //HOT
  {CONFUSED, GLAD, UWU}, //OWO
  {GRIN, UNSURE, INVALID_FACE}, //POLITE
  {DEAD, UNSURE, INVALID_FACE}, //SHOCK
  {DEAD, INVALID_FACE, INVALID_FACE}, //SKULL
  {CONFUSED, FROWN, GRIN}, //SPEECHLESS
  {HAPPY, INVALID_FACE, INVALID_FACE}, //SURPRISED
  {AHEGAO, POLITE, INVALID_FACE}, //UNSURE
  {GLAD, OWO, INVALID_FACE} //UWU
};
